apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: nginx-2
      labels:
        env: Production
        app: myapp
        type: front-end
    spec:
      containers:
         - name: nginx-contianers 
           image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end